services:
  - type: web
    name: ai-code-review-backend
    env: python
    region: oregon
    plan: starter
    branch: main
    root: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        value: "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"
      - key: MONGODB_URL
        value: "mongodb+srv://admin:admin1234@cluster0.zr9sybl.mongodb.net/?appName=Cluster0"
      - key: GITHUB_TOKEN
        value: "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"
      - key: GROQ_MODEL
        value: "llama-3.3-70b-versatile"

  - type: static
    name: ai-code-review-frontend
    env: static
    region: oregon
    plan: starter
    branch: main
    root: frontend
    buildCommand: npm install && npm run build
    publishPath: build
    envVars:
      - key: https://code-scan-backend-0zmj.onrender.com
        value: ""
